server:
  port: 9000


spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: pilot
        uri: http://localhost:9200
        predicates:
          - Path=/pilot/**
        filters:
          - RewritePath=/pilot/(?<remaining>.*),/$\{remaining}
      routes[1]:
        id: training
        uri: http://localhost:9300
        predicates:
          - Path=/training/**
        filters:
          - RewritePath=/training/(?<remaining>.*),/$\{remaining}
      routes[2]:
        id: weather
        uri: http://localhost:9100
        predicates:
          - Path=/weather/**
        filters:
          - RewritePath=/weather/(?<remaining>.*),/$\{remaining}



#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka